### ISSUE TITLE
LoRa_Repeats increases string / line number

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#10]
Hi, with LoRa_Repeats set to 2 the line number is increased by 1 for the repeated string.

I would expect the same line to be sent twice.

Might also be the case for RTTY_repeats but not tested yet.

**Comment by RoelKroes** [comment]
Fair point but I thought about this and decided to not change this as when changed, there is no way to distinguish between the transmissions and also there will be no way to see the total number of transmissions.
