### ISSUE TITLE
 M0RPI gateway

### ISSUE THREAD

**Issue by alkolbender** [RoelKroes/TBTracker#13]
Lora modul not work this gateway https://github.com/PiInTheSky/lora-gateway
my telemetry sent  $$CC5XYZ,805326032,00:00:00,0.00000,0.00000,0,0,27.6,4.76,0.00*547B
other tracker sent   ID,Ctr,Time,Lat,Lon,Alt,Speed,Head,Sats,Int.Temp  ($$CC2XYZ,6,00:00:00,0.00000,0.00000,00000,0,0,0,35.2*490D) its work 

can you help me what is the value i need to change

**Comment by RoelKroes** [comment]
I do not have this gateway and cannot test it. Is there an error message?
