### ISSUE TITLE
Radio.ino: error: 'ERR_NONE' was not declared in this scope

### ISSUE THREAD

**Issue by star210** [RoelKroes/TBTracker#15]
Hi 

I am trying to compile the code for a Atmega328PU and get the following error:

Radio.ino: In function 'void SetupFSK()':
Radio:63:15: error: 'ERR_NONE' was not declared in this scope

So when there is no error it will display the debug text to the serial monitor but I cant see where ERR_NONE is defined?

Am I missing something? I have both recommended librarys installed. 

Thanks

**Comment by RoelKroes** [comment]
Hi,

It seems that the status codes in the latest radiolib library have updated.
Try changing ERR_NONE to RADIOLIB_ERR_NONE and let me know if that works for you.

Roel.

**Comment by star210** [comment]
Hi 
I changed to RADIOLIB_ERR_NONE as suggested and it now compiles.
Thankyou Roel.

**Comment by RoelKroes** [comment]
Thanks for reporting it, I will change the code for this.

Roel.
