### ISSUE TITLE
Adding Field List to allow Sondehub support

### ISSUE THREAD

**Issue by KevWal** [RoelKroes/TBTracker#19]
Hi Roel

A placeholder for fieldlist support to allow Sondehub to understand extra data as per:

https://www.daveakerman.com/?p=2987

I may have a look at implimenting in the comming weeks

Cheers
Kev

**Comment by RoelKroes** [comment]
Hi Kev,

Thanks for letting me know!  
I've seen that and indeed an excellent idea from Dave,

I already implemented the code for that last week and tested it. I will release the code this week.
I also updated the code to be fully compatible with TinyGS.
Luckily a minor change, only like 5 lines of code, so no memory problems :-)

Best
Roel.

**Comment by KevWal** [comment]
Fantastic thanks Roel, looking forward to testing it when you are ready!

**Comment by RoelKroes** [comment]
I Added the support for (optional) transmitting METADATA compatible with lora-gateway from Dave Akerman and Sondehub. 

Best,
Roel.
