### ISSUE TITLE
2 lines need update in the software TBTracker.ini

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#3]
Line 38 #define PIN_BUSY  9
Line 39 #define PIN_RESET 7 

For the SR1278 and RFM modules neither pin 9 nor pin 7 needs to be connected. Pin 7 is also claimed for GPS software serial connection. Both pins should be set to -1 and only added when the 1262 with tcxo gets supported and needs either one of those pins.

**Comment by RoelKroes** [comment]
Thank you and correct. I changed this in the code. These pins are for other modules.
