### ISSUE TITLE
TBTracker.ino should mention the payload format / details

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#4]
At this moment there is no explanation of the variables used in the transmitted string.

There should be a line which says which parameters are transmitted, to create a payload doc in an easy way.

(like "callsign, string number, time, lat, long, alt, number of satellites and so on)

**Comment by RoelKroes** [comment]
Added comments about how to generate a payload document at habhub. Made comments about the fields in the payload sentence.
