### ISSUE TITLE
Sleep works only one time and does not allow TX_LOOP_TIME > 31 seconds

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#6]
Hi, viewing the serial output with sleep enabled I notice that after the first transmission the Atmel goes to sleep for the given number of seconds, than wakes up, starts the next transmission, goes to sleep again but wakes up in the same second.

Second issue about the same sleep function: With TX_LOOP_TIME set to anything above 32 seconds the value of TX_LOOP_TIME * 1000 gets out of range, gives a warning in the compiler but does program the software which does not ever gets back to transmit again.

![awake_to_soon](https://user-images.githubusercontent.com/4477734/71770126-99e04d80-2f29-11ea-828a-16b720466877.png)
![overflow_sleep](https://user-images.githubusercontent.com/4477734/71770131-a2388880-2f29-11ea-83d3-8c8fdc90569f.png)

**Comment by RoelKroes** [comment]
Fixed issue with deep sleep and integer out of range. Thanks for testing!
