### ISSUE TITLE
DC voltage input on A1 needs external capacitor ?

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#7]
Hi,
During the flight yesterday the battery voltage appeared to be jumpy. Tried this morning with 100nF capacitor over A1 to ground and all is very stable now. It might be the RF power from the transmitter interfering so I would add a capactior to the wiring diagram for the external voltage input.

**Comment by RoelKroes** [comment]
Thanks. And as we all know, life is always better with capacitors. Added it to the wiring instructions.
