### ISSUE TITLE
LoRa only transmits in mode 2 and 3

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#8]
When set to 0 or 1 the LoRa module does not tranmit.

Mode 2 and 3 do work good.

**Comment by RoelKroes** [comment]
Mode 0 and 1 are not implemented yet.

**Comment by RoelKroes** [comment]
TBTracker supports as version 0.1.0:

LoRa HAB Mode: 0, 1, 2, 3 and 5.
