### ISSUE TITLE
RTTY works on 50, 100, 150 and 200 baud but not (rigth) on 75 baud

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#9]
When transmitting at 75 baud this is the output in DL-FLDIGI

$$$$$bz-rttybeacon-jo21cx,0,14:27:54,51.99164,4.19875,7,6,3RV+M1A9AA)IAC
(no checksum, no green in dl-fldigi

When transmitting at 50,100,150,200 baud this is the output, as expected:

$$$$$bz-rttybeacon-jo21cx,0,14:31:13,51.99159,4.19890,15,6,32.5,3.33,0.00*BD72

Any idea ?

**Comment by RoelKroes** [comment]
Seems to work again after installing new radiolib library.
